from datetime import timedelta


# ── Application ──
VERSION = "0.1.0"


# ── Severities ──
SEVERITY_INFO = "INFO"
SEVERITY_WARN = "WARN"
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_RECOVERED = "RECOVERED"


# ── Source identifiers ──
SOURCE_SSH = "ssh"
SOURCE_SUDO = "sudo"
SOURCE_DOCKER = "docker"
SOURCE_SYSTEMD = "systemd"
SOURCE_NETWORK = "network"
SOURCE_SHUTDOWN = "shutdown"
SOURCE_CPU = "cpu"
SOURCE_RAM = "ram"
SOURCE_DISK = "disk"
SOURCE_TEMPERATURE = "temperature"
SOURCE_DAEMON = "daemon"


# ── Event types ──
EVENT_SSH_LOGIN = "SSH_LOGIN"
EVENT_SSH_LOGOUT = "SSH_LOGOUT"
EVENT_SSH_BRUTEFORCE = "SSH_BRUTEFORCE"
EVENT_SUDO_USED = "SUDO_USED"
EVENT_CONTAINER_STARTED = "CONTAINER_STARTED"
EVENT_CONTAINER_STOPPED = "CONTAINER_STOPPED"
EVENT_CONTAINER_DIED = "CONTAINER_DIED"
EVENT_CONTAINER_RESTARTED = "CONTAINER_RESTARTED"
EVENT_SERVICE_STARTED = "SERVICE_STARTED"
EVENT_SERVICE_STOPPED = "SERVICE_STOPPED"
EVENT_SERVICE_FAILED = "SERVICE_FAILED"
EVENT_SERVICE_RESTARTED = "SERVICE_RESTARTED"
EVENT_INTERFACE_UP = "INTERFACE_UP"
EVENT_INTERFACE_DOWN = "INTERFACE_DOWN"
EVENT_DAEMON_START = "DAEMON_START"
EVENT_SHUTDOWN_STARTED = "SHUTDOWN_STARTED"
EVENT_REBOOT_STARTED = "REBOOT_STARTED"
EVENT_TEMP_WARN = "TEMP_WARN"
EVENT_TEMP_CRITICAL = "TEMP_CRITICAL"
EVENT_TEMP_RECOVERED = "TEMP_RECOVERED"
EVENT_CPU_HIGH = "CPU_HIGH"
EVENT_CPU_RECOVERED = "CPU_RECOVERED"
EVENT_RAM_HIGH = "RAM_HIGH"
EVENT_RAM_RECOVERED = "RAM_RECOVERED"
EVENT_DISK_WARN = "DISK_WARN"
EVENT_DISK_CRITICAL = "DISK_CRITICAL"
EVENT_DISK_RECOVERED = "DISK_RECOVERED"


# ── Default poller intervals (seconds) ──
DEFAULT_CPU_INTERVAL = 15
DEFAULT_RAM_INTERVAL = 30
DEFAULT_TEMP_INTERVAL = 30
DEFAULT_DISK_INTERVAL = 300


# ── Default thresholds ──
DEFAULT_CPU_WARN = 80
DEFAULT_CPU_CRITICAL = 95
DEFAULT_RAM_WARN = 85
DEFAULT_RAM_CRITICAL = 95
DEFAULT_DISK_WARN = 85
DEFAULT_DISK_CRITICAL = 95
DEFAULT_TEMP_WARN = 75
DEFAULT_TEMP_CRITICAL = 85


# ── Default cooldowns (seconds) ──
DEFAULT_COOLDOWN_SSH_LOGIN = 0
DEFAULT_COOLDOWN_SSH_LOGOUT = 0
DEFAULT_COOLDOWN_SSH_BRUTEFORCE = timedelta(minutes=5).total_seconds()
DEFAULT_COOLDOWN_SUDO_USED = 0
DEFAULT_COOLDOWN_CPU_HIGH = timedelta(minutes=5).total_seconds()
DEFAULT_COOLDOWN_CPU_RECOVERED = timedelta(minutes=5).total_seconds()
DEFAULT_COOLDOWN_TEMP_WARN = timedelta(minutes=5).total_seconds()
DEFAULT_COOLDOWN_TEMP_CRITICAL = timedelta(minutes=5).total_seconds()
DEFAULT_COOLDOWN_DISK_WARN = timedelta(hours=1).total_seconds()
DEFAULT_COOLDOWN_DISK_CRITICAL = timedelta(hours=1).total_seconds()
DEFAULT_COOLDOWN_RAM_HIGH = timedelta(minutes=5).total_seconds()


# ── Dispatcher ──
DISPATCHER_QUEUE_TIMEOUT = 1.0
